#!/usr/bin/env zsh

echo "Installing apps ..."
  curl -L https://raw.github.com/fungibleclouds/laptop/master/preparation.sh | zsh

echo "Installing Postgres, a good open source relational database ..."
  brew install postgres --no-python
  initdb /usr/local/var/postgres -E utf8
  
echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "Installing tmux, a good way to save project state and switch between projects ..."
  brew install tmux

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing QT, used by Capybara Webkit for headless Javascript integration testing ..."
  brew install qt

echo "Installing Heroku toolbelt to interact with the http://heroku.com API ..."
  brew install wget
  wget http://assets.heroku.com/heroku-toolbelt/heroku-toolbelt.pkg
  sudo installer -pkg  ./heroku-toolbelt.pkg -target /
  rm -rf heroku-toolbelt.pkg

git config --global alias.co checkout
git config --global alias.br branch  
git config --global alias.st status
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
# usage
# git lg
# git lg -p

sudo scutil --set ComputerName "iMac"
sudo scutil --set HostName "iMac"
sudo scutil --set LocalHostName "iMac"

defaults write NSGlobalDomain AppleEnableMenuBarTransparency -bool false
defaults write com.apple.finder WarnOnEmptyTrash -bool false
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
defaults write com.apple.finder AppleShowAllFiles OFF
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true
chflags nohidden ~/Library
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
for app in "Address Book" "Contacts" "iCal" "Calendar" "Dock" "Finder" "Mail" "Safari" "iTunes" "SystemUIServer" "Terminal" "Twitter"; do killall "$app" > /dev/null 2>&1; done
